name: time2Travel
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependency_overrides:
  intl: ^0.18.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.

  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1

  # network image
  cached_network_image: ^3.2.3

  # Functional programming thingies
  dartz: ^0.10.1
  equatable: ^2.0.5

  # Use as Network Client
  dio: ^5.3.0

  # Use hive to save local data
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Dependencies Injection
  get_it: ^7.6.0

  # State Management
  flutter_bloc: ^8.1.3

  # responsive UI, 
  flutter_screenutil: ^5.8.4

  # router
  go_router: ^10.0.0

  # cantry picker
  list_country_picker: ^0.0.1
  phone_text_field: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  lint: ^2.1.2
  flutter_lints: ^2.0.2
  bloc_test: ^9.1.3
  http_mock_adapter: ^0.4.4

  #Temporary using old version because error when generate build_runner
  mockito: ^5.4.2

  # hive generator
  hive_generator: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

